### ISSUE TITLE
[Feature Req] allow pasting of images

### ISSUE THREAD

**Issue by tominabox1** [airmessage/airmessage-web#1]
I've been loving using Air Message web but it would be great if I could paste images into the text box to be sent like I can on android.

**Comment by tagavari** [comment]
Thanks for the feature request! This feature was added just recently in [commit 8c2c9e8](https://github.com/airmessage/airmessage-web/commit/8c2c9e8f63d77028c3226b8f5de49d575d46cd38), and it should be part of the next update.
