### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by Hoodgail** [airmessage/airmessage-web#22]
A way to view replied messages and to be able to reply to a message.
<img width="204" alt="image" src="https://user-images.githubusercontent.com/45743294/178869181-768e0879-f7d8-4c78-b5f6-e87b1d3def58.png">
Like discord for example, they have a simpler spline for referencing an old message

**Comment by py660** [comment]
I believe that replying is protected by an apple security feature (System Integrity Protection IIRC, which prevents direct access to the iMessage API). To disable SIP, you'd have to essentially jailbreak your mac, so I doubt that this change will be implemented.
