### ISSUE TITLE
Login on Firefox seems to be broken

### ISSUE THREAD

**Issue by JosephM101** [airmessage/airmessage-web#31]
Firefox is my primary browser everywhere, including on my Mac. Attempting to setup the server with my Google account, if the login was opened in Firefox, would fail every time. It wasn't until I forced it to use Safari that it worked. It's the same on my PC if I use AirMessage Web. I have to use Brave to log in because for some reason, logging in on Firefox is broken.

The issue is that it keeps springing back to the login page, failing to register that I logged in through Google. This is kind of annoying, because I don't want to run another browser to use AirMessage Web. Is there something that needs to be patched? Is there a setting I need to change?

**Comment by tagavari** [comment]
I've discovered that Firefox's built-in Enhanced Tracking Protection is incompatible with the Google Sign-In library used by the web app - please try disabling it to see if it will allow you to sign in.

You can re-enable ETP once you're signed in.

**Comment by JosephM101** [comment]
> I've discovered that Firefox's built-in Enhanced Tracking Protection is incompatible with the Google Sign-In library used by the web app - please try disabling it to see if it will allow you to sign in.
> 
> You can re-enable ETP once you're signed in.

Yup, that worked. Thanks! It's weird, because I haven't had that problem when signing in to other Google services, or services that use a Google account.
